.\" mdoc format
.Dd 31 July, 2024
.Dt NETCALC 1 
.Os
.Sh NAME
.Nm netcalc
.Nd IP subnet calculator
.Sh SYNOPSIS
.Nm
.Op opts
.Op Ar args
.Ss Options
.Nm
.Op Fl cehnrv
.Op Fl s Ar MASKLEN
.Op Fl S Ar LEN
.Op ..
.Ss Arguments
.Nm
.Op opts
.Ar NETWORK Oo Ar NETMASK Oc Op ..
.Nm
.Op opts
.Ar NETWORK/LEN Op ..
.Nm cat FILE | Nm Oo opts Oc Ar -
.Sh DESCRIPTION
.Nm
is a simple network calculator derived from
.Xr sipcalc 1 .
.Nm
takes an IP address and a subnet mask, or an IP address and prefix mask
in CIDR notation and outputs information about the subnet.  Both IPv4
and IPv6 addresses are supported.
.Sh FEATURES
.Bl -bullet -width 1n -compact
.It
Multiple address and netmask input formats
.It
Classful and CIDR output
.It
Output of broadcast address, network class, Cisco wildcard,
hosts/range, network range
.It
Output of multiple types of bitmaps
.It
Support for multiple networks input from commandline
.It
Support for reading networks from standard input (newline separated)
.It
Ability to split a network into smaller ones
.It
Compressed and expanded IPv6 input addresses
.It
Compressed and expanded IPv6 output
.It
Support for v4 in v6 output
.El
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c
Validate (check) IP address argument
.It Fl e
IPv4 compatible IPv6 information
.It Fl h
Print a summary of the options and exit
.It Fl n
Disable (no) colorization of output
.It Fl r
IPv6 reverse DNS output
.It Fl R Ar MIN:MAX
Show offset IPv4 network Range from MIN to MAX
.It Fl s Ar MASKLEN
Split the IPv4 network into subnets of MASKLEN size, where MASKLEN is
either in netmask (dotted quad) or prefix length format (/LEN)
.It Fl S Ar LEN
Split the IPv6 network into subnets of LEN size, where LEN is in prefix
length format (/LEN)
.It Fl v
Show version information
.El
.Pp
IPv4 (network) addresses must be given in standard dotted quad format,
i.e., xxx.xxx.xxx.xxx with an optional netmask that can be given in
three different ways:
.Pp
.Bl -bullet -width 1n -compact
.It
CIDR, e.g. /n, where n >= 0 <= 32
.It
Dotted quad, e.g. xxx.xxx.xxx.xxx
.It
A hexadecimal value, e.g. 0xnnnnnnnn or nnnnnnnn
.El
.Pp
IPv6 addresses may be given in any of the forms defined in RFC2373, the
netmask (prefix) must be given in CIDR notation.  Valid values for the
netmask range from n >= 0 <= 128, default value if netmask is omitted is
128.
.Pp
.Nm
also supports reading networks from stdin, this can be useful for using
.Xr cat 1
on a list of addresses stored in a file.  Each line should contain an
address netmask pair or address/len tuple.
.Sh BUGS
Use the project page to file bug reports, feature requests, patches, or
questions at
.Lk https://github.com/troglobit/netcalc GitHub
.Sh AUTHORS
.An Simon Ekstrand Ao mailto:simon@routemeister.net Ac Nm (sipcalc)
.An Joachim Wiberg Ao mailto:troglobit@gmail.com Ac Nm (netcalc)
