.\" To process this file use: groff -man -Tascii netcalc.1
.Dd 26 March, 2017
.Dt NETCALC 1 
.Os
.Sh NAME
.Nm netcalc
.Nd IP subnet calculator
.Sh SYNOPSIS
.Nm
.Op Fl cehnrv
.Op Fl s Ar MASK
.Op Fl S Ar MASK
.Aq Ar ADDRESS/LEN | Ar - | Ar NETWORK Op Ar NETMASK
.Sh DESCRIPTION
.Nm
is a simple network calculator derived from
.Nm sipcalc.
.Nm
takes an IP address and a subnet mask, or an IP address and prefix mask
in CIDR notation and outputs information about the subnet.  Both IPv4
and IPv6 addresses are supported.
.Sh FEATURES
.Bl -bullet -width 1n -compact
.It
Multiple address and netmask input formats
.It
Classful and CIDR output
.It
Output of broadcast address, network class, Cisco wildcard,
hosts/range, network range
.It
Output of multiple types of bitmaps
.It
Support for multiple networks input from commandline
.It
Support for reading newline separated list of networks from standard input (STDIN)
.It
Ability to split a network into smaller ones
.It
Compressed and expanded IPv6 input addresses
.It
Compressed and expanded IPv6 output
.It
Support for v4 in v6 output
.El
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c
Validate (check) IP address argument.
.It Fl e
IPv4 compatible IPv6 information
.It Fl h
Print a summary of the options and exit
.It Fl n
Disable (no) colorization of output.
.It Fl r
IPv6 reverse DNS output
.It Fl s Ar MASK
Split the IPv4 network into subnets of MASK size
.It Fl S Ar MASK
Split the IPv6 network into subnets of MASK size
.It Fl v
Show version information
.El
.Pp
IPv4 (network) addresses must be given in standard dotted quad format,
i.e., xxx.xxx.xxx.xxx with an optional netmask that can be given in
three different ways:
.Pp
.Bl -bullet -width 1n -compact
.It
CIDR, e.g. /n, where n >= 0 <= 32
.It
Dotted quad, e.g. xxx.xxx.xxx.xxx
.It
A hexadecimal value, e.g. 0xnnnnnnnn or nnnnnnnn
.El
.Pp
IPv6 addresses may be given in any of the forms defined in RFC2373, the
netmask (prefix) must be given in CIDR notation.  Valid values for the
netmask range from n >= 0 <= 128, default value if netmask is omitted is
128.
.Pp
.Nm
also accepts arguments from stdin, this can be useful for using
.Xr cat 1
on a list of addresses stored in a file.  Each line should contain an
address netmask pair or address/len tuple.  In this mode colorization
is automatically disabled.
.Sh BUGS
Use the project's GitHub page to file bug reports, feature requests or
patches (preferably as GitHub pull requests!), or questions at
.Aq https://github.com/troglobit/netcalc
.Sh AUTHORS
.Bl -tag -width "Simon Ekstrand mailto:simon@routemeister.net" -compact
.It Simon Ekstrand Aq mailto:simon@routemeister.net Nm (sipcalc)
.It Joachim Nilsson Aq mailto:troglobit@gmail.com Nm (netcalc)
